### ISSUE TITLE
Add Filtering

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-ideas#39]
Add simple filtering by string match, or by choosing a chip.

**Comment by allthesignals** [comment]
Need design guidance from @andycochran

**Comment by allthesignals** [comment]
Should filtering by stateful? Through query parameters? For example, `/ideas?categories=neighborhood-improvement,housing,webmapping`.

**Comment by andycochran** [comment]
Should I stub in some UI?

**Comment by allthesignals** [comment]
@andycochran sounds great!

**Comment by allthesignals** [comment]
Branch here: https://github.com/NYCPlanning/labs-ideas/tree/wmg/39-add-filtering. 

Filtering logic is: if any selected category matches any of the strategic_objectives multi-select categories of each Idea. 

It doesn't combine multiple categories into one, yet - we should figure out exactly what those will be.

**Comment by andycochran** [comment]
I checked this out and took a look. I was gonna fix the grid layout of the filters. But we should probably merge master before it gets too messy. 

I'd also recommend using buttons instead of labels: 

```
<button type="button" class="button [strategic-objective] [hollow]">Save</button>
```

We'll need to add the same colors from the `$label-palette` map to the `$button-palette` map so that the `[strategic-objective]` classes will work. The `hollow` class can be applied to the unselected buttons, which will style 'em like this:

![image](https://user-images.githubusercontent.com/409279/28503477-8f990774-6fd5-11e7-9e65-66395e9af452.png)
http://foundation.zurb.com/sites/docs/button.html#hollow-style

**Comment by allthesignals** [comment]
@andycochran I can switch to buttons, but is there anything else for the design? Do you want to work off this branch to implement?

**Comment by andycochran** [comment]
@allthesignals Oh, you might also want to all the `tiny` class to the buttons. We can reevaluate the UI, maybe when/if we introduce user-submitted text filtering.

**Comment by allthesignals** [comment]
Closed by https://github.com/NYCPlanning/labs-ideas/pull/49
